Handle invalid git repositories
The code trusted on the existence of the repository path to consider
it a valid git repository.  However, this is not true if a previous
non-git repository existed, e.g. an svn repository.  The following
exception is raised on this situation:

Traceback (most recent call last):
  File "host_os.py", line 81, in <module>
    SUBCOMMANDS[subcommand].run(CONF)
  File "/home/jenkins/workspace/build_host_os/tools/build_packages.py", line 42, in run
    bm.build()
  File "/home/jenkins/workspace/build_host_os/lib/build_manager.py", line 97, in build
    self._build_packages(self.distro, ordered_packages)
  File "/home/jenkins/workspace/build_host_os/lib/build_manager.py", line 66, in _build_packages
    package.download_files(recurse=False)
  File "/home/jenkins/workspace/build_host_os/lib/package.py", line 167, in download_files
    local_copy_subdir_name=self.name)
  File "/home/jenkins/workspace/build_host_os/lib/package_source.py", line 164, in download
    return _git_download(source, directory)
  File "/home/jenkins/workspace/build_host_os/lib/package_source.py", line 94, in _git_download
    error=exception.RepositoryError)
  File "/home/jenkins/workspace/build_host_os/lib/utils.py", line 54, in retry_on_error
    return f()
  File "/home/jenkins/workspace/build_host_os/lib/package_source.py", line 91, in _download_repository
    return repository.get_git_repository(git_source['src'], directory)
  File "/home/jenkins/workspace/build_host_os/lib/repository.py", line 53, in get_git_repository
    repo = GitRepository(repo_path)
  File "/home/jenkins/workspace/build_host_os/lib/repository.py", line 114, in __init__
    super(GitRepository, self).__init__(repo_path, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git/repo/base.py", line 167, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /var/lib/host-os/repositories/gcc

With this change, if git.exc.InvalidGitRepositoryError is thrown, the
exception is logged and raised so user will need to know what to do;
if git.exc.NoSuchPathError is thrown, a fresh git-clone is performed.

Signed-off-by: Murilo Opsfelder Araujo <muriloo@linux.vnet.ibm.com>