Add PyYAML in requirements-dev.txt
The PyYAML is missing from requirements-dev.txt, causing nosetests to
fail due python import error:

$ nosetests tests/unit/config_tests.py
E
======================================================================
ERROR: Failure: ImportError (No module named yaml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/muriloo/sources/mopsfelder/open-power-host-os/builds/venv/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/muriloo/sources/mopsfelder/open-power-host-os/builds/venv/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/muriloo/sources/mopsfelder/open-power-host-os/builds/venv/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/muriloo/sources/mopsfelder/open-power-host-os/builds/tests/unit/config_tests.py", line 5, in <module>
    from lib.config import ConfigParser
  File "/home/muriloo/sources/mopsfelder/open-power-host-os/builds/lib/config.py", line 21, in <module>
    import yaml
ImportError: No module named yaml

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

Signed-off-by: Murilo Opsfelder Araujo <muriloo@linux.vnet.ibm.com>