lib/repository.py: Call git command to update submodules
GitPython assumes that a default reference, branch_path=refs/heads/master, will
exist on the submodule repository. However, this is not true for all cases. For
example, seabios-hppa submodule of qemu only has parisc_firmware branch and
GitPython fails to update seabios-hppa submodule:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/site-packages/git/objects/submodule/base.py", line 520, in update
        remote_branch = find_first_remote_branch(mrepo.remotes, self.branch_name)
      File "/usr/lib/python2.7/site-packages/git/objects/submodule/util.py", line 38, in find_first_remote_branch
        raise InvalidGitRepositoryError("Didn't find remote branch '%r' in any of the given remotes" % branch_name)
    git.exc.InvalidGitRepositoryError: Didn't find remote branch ''master'' in any of the given remotes

This fixes the issue by calling git command directly from the git.Repo object,
which uses the HEAD reference from the cloned submodule repository. Thus, we
don't need to worry about if refs/heads/master exists on the submodule
repository and GitPython succeeds to update repository submodules.

Thanks to Fabiano Almeida Rosas that helped on this troubleshooting.